<?php

/**
 * Implements hook_uninstall().
 */
function social_likes_uninstall() {
  variable_del('social_likes_skin');
  variable_del('social_likes_custom');
  variable_del('social_likes_look');
  variable_del('social_likes_labels');
  variable_del('social_likes_websites');
  variable_del('social_likes_url');
  variable_del('social_likes_title');
  variable_del('social_likes_via');
  variable_del('social_likes_related');
  variable_del('social_likes_image_url');
}
