<?php
/**
 * @file
 * Main file for the Social Likes Next module.
 */

/**
 * Returns all social networks with supported features.
 */
function social_likes_social_networks_list() {
  return array(
    'facebook'      => t('Facebook'),
    'twitter'       => t('Twitter'),
    'plusone'       => t('Google+'),
    'pinterest'     => t('Pinterest'),
    'telegram'      => t('Telegram'),
    'linkedin'      => t('LinkedIn'),
    'vkontakte'     => t('Vkontakte'),
    'odnoklassniki' => t('Odnoklassniki'),
  );
}

/**
 * Implements hook_menu().
 */
function social_likes_menu() {
  $items = array();

  $items['admin/config/services/social_likes'] = array(
    'title' => 'Social Likes Next',
    'description' => 'Configure Social Likes Next widget.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('social_likes_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'social_likes.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_field_extra_fields().
 */
function social_likes_field_extra_fields() {
  $social_likes_fields = array();

  foreach (node_type_get_types() as $type) {
    $social_likes_fields['node'][$type->type]['display']['social_likes'] = array(
      'label' => t('Social Likes Next'),
      'description' => t('Social Likes Next'),
      'weight' => 50,
    );
  }

  return $social_likes_fields;
}

/**
 * Implements hook_node_view().
 */
function social_likes_node_view($node, $view_mode, $langcode) {
  static $social_likes_fields = array();

  $key = 'node:' . $node->type . ':' . $view_mode;
  if (!isset($social_likes_fields[$key])) {
    $social_likes_fields[$key] = field_extra_fields_get_display('node', $node->type, $view_mode);
  }

  $element = social_likes_element_info()['social_likes_widget'];

  if (isset($social_likes_fields[$key]['social_likes']) && $social_likes_fields[$key]['social_likes']['visible']) {
    $node->content['social_likes']['#type'] = 'social_likes_widget';

    if (isset($element['#url'])) {
      $node->content['social_likes']['#url'] = token_replace($element['#url'], array('node' => $node));
    }

    if (isset($element['#title'])) {
      $node->content['social_likes']['#title'] = token_replace($element['#title'], array('node' => $node));
    }
  }
}

/**
 * Implements hook_element_info().
 */
function social_likes_element_info() {
  $types = array();

  $types['social_likes_widget'] = array(
    '#input' => FALSE,
    '#pre_render' => array('social_likes_widget_pre_render'),
    // Appearance.
    '#skin' => variable_get('social_likes_skin', 'flat'),
    '#custom' => variable_get('social_likes_custom', 'sites/all/modules/social_likes/css/social-likes_example.css'),
    '#look' => variable_get('social_likes_look', FALSE),
    '#labels' => variable_get('social_likes_labels', FALSE),
    // Display output.
    '#websites' => variable_get('social_likes_websites', drupal_map_assoc(array('facebook', 'twitter', 'vkontakte'))),
    '#url' => variable_get('social_likes_url', '[node:url]'),
    '#title' => variable_get('social_likes_title', '[node:title]'),
    '#via' => variable_get('social_likes_via', ''),
    '#related' => variable_get('social_likes_related', ''),
    '#image_url' => variable_get('social_likes_image_url', ''),

  );

  return $types;
}

function social_likes_widget_pre_render($element) {
  $element['#theme'] = 'social_likes_widget';

  $element['#label'] = social_likes_social_networks_list();
  $element['#look'] = $element['#look'] ? 'social-likes_vertical' : '';
  $element['#websites'] = array_diff($element['#websites'], array(0));
  $element['#url'] = $element['#url'] ? $element['#url'] : '';
  $element['#title'] = $element['#title'] ? $element['#title'] : '';
  $element['#via'] = $element['#via'] ? $element['#via'] : '';
  $element['#related'] = $element['#related'] ? $element['#related'] : '';
  $element['#image_url'] = $element['#image_url'] ? $element['#image_url'] : '';

  $skin = $element['#skin'];
  $custom = $element['#custom'];
  if ($skin == 'custom') {
    $skin_css = $custom;
  }
  else {
    $skin_css = drupal_get_path('module', 'social_likes') . '/dist/social-likes_' . $skin . '.css';
  }

  $element['#attached'] = array(
      'js' => array(drupal_get_path('module', 'social_likes') . '/dist/social-likes.min.js' => array('type' => 'file', 'scope' => 'footer')),
      'css' => array($skin_css)
  );

  return $element;
}

/**
 * Implements hook_theme().
 */
function social_likes_theme() {
  return array(
    'social_likes_widget' => array(
      'render element' => 'element',
      'template' => 'templates/social_likes_widget',
    ),
  );
}
